# Generated by Django 4.2.16 on 2024-09-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=8)),
                ('local', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=8)),
                ('staus', models.CharField(choices=[('Dísponivel', 'Dísponivel'), ('Indíponivel', 'Indísponivel'), ('Em Manutenção', 'Em Manutenção')], max_length=13)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleLab.laboratorio')),
            ],
        ),
    ]
