# Generated by Django 4.2.16 on 2024-10-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0002_rename_staus_computador_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleLab.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('solicitante', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('carregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleLab.carregador')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControleLab.computador')),
            ],
        ),
    ]
