# Generated by Django 4.2.16 on 2024-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0003_carregador_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='numero',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
