# Generated by Django 4.2.16 on 2024-10-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0004_computador_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='patrimonio',
            new_name='numero',
        ),
    ]
