# Generated by Django 4.2.16 on 2024-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0005_rename_patrimonio_relatorio_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='horario_devolucao',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='horario_emprestimo',
            field=models.TimeField(default='00:00'),
        ),
    ]
