# Generated by Django 4.2.16 on 2024-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0006_remove_relatorio_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='a',
            field=models.CharField(default='a', max_length=3),
        ),
    ]
