# Generated by Django 4.2.16 on 2024-10-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0007_relatorio_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='a',
        ),
    ]
