# Generated by Django 4.2.16 on 2024-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0008_remove_relatorio_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='carregador',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4),
        ),
        migrations.DeleteModel(
            name='Carregador',
        ),
    ]
