# Generated by Django 4.2.16 on 2024-10-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0009_alter_relatorio_carregador_delete_carregador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.CharField(default='01/01/0001', max_length=12),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='horario_devolucao',
            field=models.CharField(default='--:--', max_length=10),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='horario_emprestimo',
            field=models.CharField(default='--:--', max_length=10),
        ),
    ]
