# Generated by Django 4.2.16 on 2024-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0010_alter_relatorio_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='observacao',
            field=models.CharField(default='S/O', max_length=550),
        ),
    ]
