# Generated by Django 4.2.16 on 2024-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0011_relatorio_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='status',
            field=models.CharField(choices=[('Dísponivel', 'Dísponivel'), ('Indísponivel', 'Indísponivel'), ('Em Manutenção', 'Em Manutenção')], max_length=13),
        ),
    ]
