# Generated by Django 4.2.16 on 2024-10-04 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0012_alter_computador_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.CharField(default=datetime.date(2024, 10, 4), max_length=12),
        ),
    ]
