# Generated by Django 4.2.16 on 2024-11-04 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0014_alter_relatorio_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricula', models.CharField(default='0000', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.CharField(default=datetime.date(2024, 11, 4), max_length=12),
        ),
    ]
