# Generated by Django 4.2.16 on 2024-11-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0015_usuario_alter_relatorio_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
