# Generated by Django 4.2.16 on 2024-11-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ControleLab', '0016_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=70)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
