# Generated by Django 4.2.16 on 2024-11-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControleLab', '0017_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
